[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
test = 'test'
auto_detect_remappings = false
auto_detect_solc = false
ignored_warnings_from = ["test/mock_fiattoken"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
ethereum = "https://gateway.tenderly.co/public/mainnet"
ethereum_sepolia = "https://gateway.tenderly.co/public/sepolia"
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
