name: pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  merge_group:
    types: [checks_requested]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install jq
        run: sudo apt update && sudo apt install -y jq

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.10.0'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 'v1.0.0'

      - name: Install npm dependencies
        run: yarn install

      - name: Check formatting
        run: yarn format

      - name: Lint
        run: yarn lint

      - name: Ensure artifacts haven't changed
        run: |
          yarn artifacts
          if [ -n "$(git status --porcelain)" ]; then
            echo "Artifacts have changed, please commit the changes.";
            exit 1;
          fi

      - name: Check contract sizes
        run: yarn sizes

      - name: Run tests
        run: yarn test:all

  rollup_results:
    runs-on: small
    name: Build Success Rollup
    if: ${{ always() }}
    needs:
      - ci
    steps:
      - run: |
          [ "${{ needs.ci.result }}" = "success" ] || [ "${{ needs.ci.result }}" = "skipped" ]
